//! Rendering the bib linter-rules reference from rule metadata.
//!
//! The bib analog of [`crate::linter::docs`], sharing its section renderer
//! (`render_rule_section`) so the two references cannot drift in shape.
//! [`render_rule_doc`] and [`render_reference_page`] are the single source of
//! truth shared by the snapshot test (`tests/bib_rule_docs.rs`) and the docs
//! generator (`examples/docgen.rs`), so the committed
//! `docs/reference/bib-linter-rules.md` and the pinned snapshots can never
//! diverge from behavior. Every example is linted by the *real* bib driver
//! ([`demo_diagnostics`]), so the rendered diagnostics and the autofix
//! before/after always reflect the current rules.

use std::path::PathBuf;

use crate::bib::linter::check::lint_document_with_project;
use crate::bib::linter::rules::{BibRule, all_rules};
use crate::bib::parse;
use crate::bib::semantic::Model;
use crate::linter::diagnostic::Diagnostic;
use crate::linter::docs::{RuleDocSection, render_rule_section};

/// The synthetic resource loaded by a complete document with no citations.
fn example_path() -> PathBuf {
    PathBuf::from("references.bib")
}

/// Lint `source` as a self-contained `.bib` file: parse, build the semantic
/// [`Model`], and run every built-in bib rule.
pub fn demo_diagnostics(source: &str) -> Vec<Diagnostic> {
    let path = example_path();
    let root = parse(source).syntax();
    let model = Model::build(&root);
    // Explicit fixture: one complete root loads this resource with no uses.
    let project = super::project::ProjectFacts {
        complete: true,
        ..Default::default()
    };
    lint_document_with_project(&path, &root, &model, Some(&project))
}

/// Render the reference *section* for a single bib rule: an `## \`id\``
/// heading, the rule's `description()`, and each example rendered with its live
/// diagnostics and (for a safe autofix) the after state.
pub fn render_rule_doc(rule: &dyn BibRule) -> String {
    let path = example_path();
    render_rule_section(
        &RuleDocSection {
            id: rule.id(),
            description: rule.description(),
            default_enabled: rule.default_enabled(),
            examples: rule.examples(),
            companions: &[],
            example_path: &path,
            lang: "bib",
        },
        &demo_diagnostics,
    )
}

/// Render the reference section for the bib rule with `id`, or `None` if no
/// built-in bib rule has that id. Backs `tex-ls lint --explain <rule>` (after
/// the LaTeX registry misses), reusing the same live-linted rendering as the
/// docs page.
pub fn explain_rule(id: &str) -> Option<String> {
    all_rules()
        .iter()
        .find(|rule| rule.id() == id)
        .map(|rule| render_rule_doc(rule.as_ref()))
}

/// The full `bib-linter-rules.md` reference page: a static preamble, one
/// generated section per rule (registry order), and a static configuration
/// footer.
pub fn render_reference_page() -> String {
    let mut out = String::from(PREAMBLE);
    for rule in all_rules() {
        out.push('\n');
        out.push_str(&render_rule_doc(rule.as_ref()));
    }
    out.push('\n');
    out.push_str(FOOTER);
    out
}

const PREAMBLE: &str = "\
<!-- Generated by `cargo run --example docgen`. Do not edit by hand: edit each \
rule's `description()`/`examples()` in `crates/tex-ls-analysis/src/bib/linter/rules/` and regenerate. -->

# BibTeX lint rules

Each rule has an ID used by diagnostics, `select`/`ignore`, and suppression comments.
These settings also apply to the [LaTeX rules](linter-rules.md). See
[configuration](configuration.md#lint) for rule selection.

Each section states the rule's default. `tex-ls lint --fix` applies safe fixes;
`--unsafe-fixes` also permits changes to typeset output. Examples show diagnostics
and safe fixes generated by the linter.

";

const FOOTER: &str = "\
## Suppression

BibTeX has no line-comment token. Suppression directives use a structured
`@comment` entry instead of the LaTeX `%` directive. A plain directive
suppresses one rule on the **next entry**:

```bib
@comment{tex-ls-lint skip missing-required-field: publisher long gone}
@book{oldbook, title = {An Orphaned Book}}
```

As in LaTeX, `off` and `on` delimit a
region of entries, and `skip-file` covers the whole file wherever it sits:

```bib
@comment{tex-ls-lint off missing-required-field: imported, incomplete by design}
@book{oldbook, title = {An Orphaned Book}}
@comment{tex-ls-lint on missing-required-field}
```

Naming the `<id>` is optional; leaving it out suppresses every rule over that
same span. Parse diagnostics (rule id `parse`) are never suppressed.
";
